### ISSUE TITLE
Typo importing generate_default_config

### ISSUE THREAD

**Issue by mcvlad** [awslabs/neptuneml-toolkit#8]
Hello,

Note that there is typo here, the import is `generate_default_config`:
https://github.com/awslabs/neptuneml-toolkit/blob/c83eaa443968b000030a34f36501a8189d00bd8b/src/neptuneml_toolkit/client/neptune_ml_client.py#L7

And the call is `generate_config`:
https://github.com/awslabs/neptuneml-toolkit/blob/c83eaa443968b000030a34f36501a8189d00bd8b/src/neptuneml_toolkit/client/neptune_ml_client.py#L74-L75

Cheers,
Mike

**Comment by sojiadeshina** [comment]
Thanks for reporting and submitting the fix https://github.com/awslabs/neptuneml-toolkit/pull/9
